import Link from "next/link";

import { BrandLogo } from "@/components/BrandLogo";

export const metadata = { title: "Terms of Service · Bantoo Books" };

const UPDATED = "July 4, 2026";

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-2xl px-6 py-12">
      <BrandLogo href="/login" size="auth" />
      <h1 className="mt-6 text-3xl font-semibold tracking-tight">Terms of Service</h1>
      <p className="mt-1 text-sm text-[var(--muted)]">Last updated: {UPDATED}</p>

      <div className="prose-legal mt-8 space-y-6 text-sm leading-6 text-slate-700">
        <section>
          <h2 className="text-base font-semibold text-slate-900">1. Agreement</h2>
          <p>
            These Terms of Service (&ldquo;Terms&rdquo;) govern your access to and use of Bantoo
            Books (the &ldquo;Service&rdquo;), an online accounting and bookkeeping application. By
            creating an account or using the Service, you agree to these Terms. If you are using the
            Service on behalf of a business, you represent that you are authorized to bind that
            business to these Terms.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-slate-900">2. Your account</h2>
          <p>
            You are responsible for maintaining the confidentiality of your login credentials and
            for all activity under your account. You must provide accurate information and keep it up
            to date. Notify us immediately of any unauthorized use of your account.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-slate-900">3. Your data</h2>
          <p>
            You retain all rights to the financial and business data you enter into the Service
            (&ldquo;Your Data&rdquo;). You grant us a limited licence to store and process Your Data
            solely to provide and maintain the Service. You are responsible for the accuracy and
            legality of Your Data.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-slate-900">4. Acceptable use</h2>
          <p>
            You agree not to misuse the Service, including by attempting to access other
            organizations&apos; data, disrupting the Service, reverse-engineering it, or using it for
            unlawful purposes.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-slate-900">5. Not professional advice</h2>
          <p>
            Bantoo Books is a bookkeeping tool, not a substitute for professional accounting, tax, or
            legal advice. Reports and figures generated by the Service are provided for your
            convenience; you are responsible for verifying them and for your regulatory and tax
            filings.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-slate-900">6. Availability &amp; changes</h2>
          <p>
            We aim to keep the Service available but do not guarantee uninterrupted access. We may
            modify, suspend, or discontinue features, and may update these Terms; continued use after
            changes constitutes acceptance.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-slate-900">7. Liability</h2>
          <p>
            The Service is provided &ldquo;as is&rdquo; without warranties of any kind. To the
            maximum extent permitted by law, we are not liable for indirect, incidental, or
            consequential damages, or for any loss of data or profits arising from your use of the
            Service.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-slate-900">8. Termination</h2>
          <p>
            You may stop using the Service at any time. We may suspend or terminate accounts that
            violate these Terms. You may request export or deletion of Your Data as described in our{" "}
            <Link href="/privacy" className="text-[var(--brand)] hover:underline">Privacy Policy</Link>.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-slate-900">9. Contact</h2>
          <p>
            Questions about these Terms? Contact us at{" "}
            <a href="mailto:support@bantoobooks.com" className="text-[var(--brand)] hover:underline">
              support@bantoobooks.com
            </a>
            .
          </p>
        </section>
      </div>

      <div className="mt-10 border-t border-[var(--border)] pt-6 text-sm">
        <Link href="/login" className="font-medium text-[var(--brand)] hover:underline">
          ← Back to sign in
        </Link>
      </div>
    </main>
  );
}
